name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup...
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run:
        npm install
    - name: npm run release
      run:
        npm run release
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: drop-${{ matrix.os }}
        path: 'release-builds'
      env:
        CI: true
